language: cpp
sudo: false
matrix:
  include:
  - sudo: true
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    cache:
      directories:
      - "$HOME/ibex"
      - "$HOME/Downloads"
      - "$HOME/cache"
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - chmod a+x travis_script/docker_build_pyibex.sh
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis_script/docker_build_pyibex.sh
    - ls wheelhouse

  - os: osx
    env: PYTHON=2.7 CPP=14 CLANG
    install:
    - brew upgrade pyenv
    - bash ./travis_script/build_Ibex4pyIbex.sh 2>&1 1> ibex-build.log
    script:
    - chmod a+x ./travis_script/build_osx.sh
    - "./travis_script/build_osx.sh"
env:
  global:
  - secure: QMtC7zYxU4pPwZrQ4OX2bjgPoei+2PYZPxuTOGewgI11HlbM7xFbryhloHeIeoeKXjKgUhCSY32lUiAP4NlT1ZkQVVr30m7FF+6hZkw6/bFvernOdr9kAd99Hg3uiunHCKoce7tTkIpo/eLTGAmr1Vbcc0FTZNagAWZmNClGOIw=
  - secure: cKkW9x5L4KFuq3bzb9uCsYSiXo/V55m96Ua122Wo7J5BfiagJqXoPc8PcWwx/qgLrCiT2xzW4fTp1DFDq97LsaXxEp/TWvzI+zPhB4tfUDzF95Dbvkl7A+sgmmSYkBiD146WP4KjmMGEv65RzIS9nFaRikF1X790Sxy/pEAhjLY=
cache:
  directories:
  - "$HOME/ibex"
  - "$HOME/Downloads"
  - "$HOME/cache"

addons:
  ssh_known_hosts: bdesroch.privatedns.org

before_install:
- openssl aes-256-cbc -K $encrypted_566771925b72_key -iv $encrypted_566771925b72_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

after_failure: cat tests/test_cmake_build/*.log
after_success:
- cd wheelhouse
- whl=$(ls *.whl)
- echo $whl
- rsync -avP -e "ssh -p 2993 -i /tmp/deploy_rsa -oStrictHostKeyChecking=no" *.whl git@bdesroch.privatedns.org:~/gittmp/$(date +"%Y%m%d")/;
# - for w in $whl; do 
    # curl -v -k --ftp-create-dirs -T $w --key /tmp/deploy_rsa sftp://git@bdesroch.privatedns.org:2993/gittmp/$(date +"%Y%m%d")/$w;
  # done;
