language: c++

compiler:
  - gcc
  - clang

python:
  - "3.4"
# 
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y --force-yes python3.4 flex bison gcc g++ coinor-libclp-dev libcpptest-dev pkg-config
  - sudo apt-get install libpython3.4-dev libboost-python1.55-dev 

# command to install dependencies
install: 
  - ./build_Ibex4pyIbex.sh

# command to run tests
script:  
  - ./build.sh

