language: cpp
sudo: false


addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise
    - kubuntu-backports # cmake 2.8.12

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8
    - patchelf

cache:
  directories:
  - $HOME/ibex
  #- $HOME/boost_1_58_0
  - $HOME/Downloads

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    language: python
    python: "3.4"
    compiler: gcc-4.8
  - os: linux
    language: python
    python: "3.5"
    compiler: gcc-4.8

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then python -m pip install auditwheel twine; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then pip install --user wheel twine; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew install clang-omp; fi

install:
  - bash ./travis_script/build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex

# command to run tests
script:
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics
  - mkdir build
  - cd build
  - export version=$(python -c "import sys; print(sys.version[:3])")
  - echo $version
  - ls ${HOME}/ibex
  - ls ${HOME}/ibex/lib
  - if [ $TRAVIS_OS_NAME == osx ]; then
      cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} ../ ;
    fi
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} -DCMAKE_CXX_COMPILER=g++-4.8 ../ ;
    fi
  - make && make install

  - make test
  - make pip_package
  - export wheel_file=$(ls *.whl)
  # - if [  $TRAVIS_OS_NAME == linux ]; then
      # auditwheel repair $(ls *.whl);
      # export wheel_file=$(ls wheelhouse/*.whl);
    # fi

  - mv $wheel_file $TRAVIS_BUILD_DIR/$wheel_file

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PLxHkV8vz8cdPMQKOm6BDAPUZgScq3frcuWUQ0PVsB66gu2mW+tnvIQzg0duom7rv9wrOksblkAhLRh2kNh7coLnlAD5AT7Y74PUjYv6sFsv9Obh0Kvc97v4/7eVg4xOcdcvPYEiYCQ/ZfXPzpkOcUF7IRYx4KKXN9CbVpbU/W8=
  file: $TRAVIS_BUILD_DIR/$wheel_file
  prerelease: true
  on:
    branch: master
    tag: true
    # repo: benEnsta/pyIbex


# deploy:
#   provider: script
#   skip_cleanup: true
#   script: travis_script/deploy.sh
#   on:
#     branch: appveyor
#     tag: false

#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#    secure: CuUogABlVRxUKWchoCT9PI7YwEmTRBhSjTEx+8Vi5HAb9Eq4nAR+Nc3bMHM0mSmxZn9lDGTjWDOMOdpg8nw80rZi1mCepO3fYa2eVrK6YlFIvZNLbAx2u4MUCXTYmsurpUiV7Du8LSbKA942y0RDCOX27pCyDCO5jfSOj7xlQWOgoryxfjFwsuBQntHMCWp/AH1HxlmJ40KZgQl4Nha2xuIJPBt2fYSBkjsWot0nd1hVhDUFxgi7zzOMAzC+vYrdmo89EVb4PfMPDlc+2LHnT7MMo7T7KrG1muRAryoOqsVsUfKXP9QUjGzpcjNKKimhB1ZikS/3ncEpQtO4/60TUY+cUJcw/22Idn5iReBnME21kpNUxiN7PvhirAs5g9Yic2f0uCIsLHXeqSWOTkwHZKyyyPKsDH/0/0SFYSihPawPOwqUPujLBAkIeHRf1REgsWyAFgxoSEgIs8r5/8Buj8ow7Ho/kR/QTJ5IZpgg806EOd8yxMa9C4H9LprK0J9el/pOFrgYBreQjTrxNyQhnnLSqUEumkH7atG5RRRW4pUCFMtO3pJp7EvgCWgFYlxU7NXLsjTcoNE6Juhu1RrkAdbpya90FqSobQ//cmaidMZNqqwbimH7XtUPO1iS/OuselmbcgsnD3QzgMwP0V4+XWfgWdg4On9QTUG/CS0LWec=
#  file: $TRAVIS_BUILD_DIR/$wheel_file
#  on:
#    repo: benEnsta/pyIbex
#    tags: true
