language: cpp
sudo: false
matrix:
  include:
  - sudo: true
    services:
    - docker
    env: DOCKER_IMAGE=benensta/pyibex-docker
    install:
    - docker pull $DOCKER_IMAGE
    script:
    # - chmod a+x scripts/docker_build.sh
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/scripts/docker_build.sh
    - ls wheelhouse
  - name: "Python 3.7.4 on macOS"
    os: osx
    osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
    language: shell       # 'language: python' is an error on Travis CI macOS
    cache:
      directories:
      - "$HOME/ibex"
      - "$HOME/Downloads"
      - "$HOME/cache"
    install: pip3 install --upgrade pip
    script:
     - ./scripts/build_Ibex4pyIbex.sh
     - mkdir build && cd build
     - cmake -DPYTHON_EXECUTABLE=$(which python3) ..
     - make -j2
     - make test
     - make pip_package
  # - os: osx
  #   env: PYTHON=2.7 CPP=14 CLANG
  #   install:
  #   # - brew upgrade pyenv
  #   - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  #   - export PYENV_ROOT="$HOME/.pyenv"
  #   - export PATH="$PYENV_ROOT/bin:$PATH"
  #   - bash ./script/build_Ibex4pyIbex.sh 2>&1 1> ibex-build.log
  #   script:

  #   - chmod a+x ./script/build_osx.sh
  #   - "./script/build_osx.sh"
env:
  global:
  - secure: QMtC7zYxU4pPwZrQ4OX2bjgPoei+2PYZPxuTOGewgI11HlbM7xFbryhloHeIeoeKXjKgUhCSY32lUiAP4NlT1ZkQVVr30m7FF+6hZkw6/bFvernOdr9kAd99Hg3uiunHCKoce7tTkIpo/eLTGAmr1Vbcc0FTZNagAWZmNClGOIw=
  - secure: cKkW9x5L4KFuq3bzb9uCsYSiXo/V55m96Ua122Wo7J5BfiagJqXoPc8PcWwx/qgLrCiT2xzW4fTp1DFDq97LsaXxEp/TWvzI+zPhB4tfUDzF95Dbvkl7A+sgmmSYkBiD146WP4KjmMGEv65RzIS9nFaRikF1X790Sxy/pEAhjLY=
cache:
  directories:
  - "$HOME/ibex"
  - "$HOME/Downloads"
  - "$HOME/cache"
addons:
  ssh_known_hosts: bdesroch.privatedns.org
before_install:
- openssl aes-256-cbc -K $encrypted_566771925b72_key -iv $encrypted_566771925b72_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
after_failure: cat tests/test_cmake_build/*.log
after_success:
- ls
- cd wheelhouse
- whl=$(ls *.whl)
- echo $whl
- rsync -avP -e "ssh -p 2993 -i /tmp/deploy_rsa -oStrictHostKeyChecking=no" *.whl
  git@bdesroch.privatedns.org:~/gittmp/$(date +"%Y%m%d")/;

deploy:
  provider: releases
  name: pyibex-1.8.1
  api_key:
    secure: FF07W49cTs+y/ypiIcdo0nBVn46LV/MKkhOd0VbEYEMuavPklIWpk0vz0V4b3VWRn7agiRr3ZWzYLML4KzhHqBONWkeuy4F6OdhfO0JxBUEqvgZo+JUaMPraiH3lnCzrOgxDC6MH+pRPqvN5TpcpLvaqE2jLcq0mxKqIN9wwekk=

  file_glob: true
  file: ./**/*.whl
  skip_cleanup: true
  draft: true
  overwrite: true
  # on:
  #   tag: true
  #   repo: benEnsta/pyIbex
