sudo: false

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise
    - boost-latest

    packages:
    - cmake
    - time
    - pkg-config
    - libboost-python1.55-dev

compiler:
  - gcc
  - clang

python:
  - "3.4"
cache:
  directories:
  - $HOME/ibex

before_script:
  - pip install numpy
  - bash ./build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex

# command to run tests
script:  
  - bash ./build.sh

