language: c++
sudo: false


addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise
    - kubuntu-backports # cmake 2.8.12

    packages:
    - cmake
    - time
    - pkg-config
    - g++-4.8

cache:
  directories:
  - $HOME/ibex
  #- $HOME/boost_1_58_0
  - $HOME/Downloads

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    language: python
    python: "3.4"
    compiler: gcc-4.8
  - os: linux
    language: python
    python: "3.5"
    compiler: gcc-4.8

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then pip install --user wheel; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew install clang-omp; fi

install:
  - bash ./travis_script/build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex

# command to run tests
script:
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics
  - mkdir build
  - cd build
  - export version=$(python -c "import sys; print(sys.version[:3])")
  - echo $version
  - ls ${HOME}/ibex
  - ls ${HOME}/ibex/lib
  - if [ $TRAVIS_OS_NAME == osx ]; then
      # CC=clang-omp CXX=clang-omp++ cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} ../ ;
      cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} ../ ;
    fi
  - if [ $TRAVIS_OS_NAME == linux ]; then
      cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version} -DCMAKE_CXX_COMPILER=g++-4.8 ../ ;
    fi
  - make && make install
# - export PYTHONPATH=$PYTHONPATH:/home/travis/lib/python${version}/site-packages
  - make test
  - make pip_package
  - export wheel_file=$(ls *.whl)
  - mv $wheel_file $TRAVIS_BUILD_DIR/$wheel_file
  - make install_python

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CuUogABlVRxUKWchoCT9PI7YwEmTRBhSjTEx+8Vi5HAb9Eq4nAR+Nc3bMHM0mSmxZn9lDGTjWDOMOdpg8nw80rZi1mCepO3fYa2eVrK6YlFIvZNLbAx2u4MUCXTYmsurpUiV7Du8LSbKA942y0RDCOX27pCyDCO5jfSOj7xlQWOgoryxfjFwsuBQntHMCWp/AH1HxlmJ40KZgQl4Nha2xuIJPBt2fYSBkjsWot0nd1hVhDUFxgi7zzOMAzC+vYrdmo89EVb4PfMPDlc+2LHnT7MMo7T7KrG1muRAryoOqsVsUfKXP9QUjGzpcjNKKimhB1ZikS/3ncEpQtO4/60TUY+cUJcw/22Idn5iReBnME21kpNUxiN7PvhirAs5g9Yic2f0uCIsLHXeqSWOTkwHZKyyyPKsDH/0/0SFYSihPawPOwqUPujLBAkIeHRf1REgsWyAFgxoSEgIs8r5/8Buj8ow7Ho/kR/QTJ5IZpgg806EOd8yxMa9C4H9LprK0J9el/pOFrgYBreQjTrxNyQhnnLSqUEumkH7atG5RRRW4pUCFMtO3pJp7EvgCWgFYlxU7NXLsjTcoNE6Juhu1RrkAdbpya90FqSobQ//cmaidMZNqqwbimH7XtUPO1iS/OuselmbcgsnD3QzgMwP0V4+XWfgWdg4On9QTUG/CS0LWec=
  file: $TRAVIS_BUILD_DIR/$wheel_file
  on:
    repo: benEnsta/pyIbex
    tags: true
