version: 1.5.0rc3
os: Visual Studio 2015
clone_folder: C:\projects\pyIbex
test: off
configuration:
    - Release
    # - Debug
# branches:
  # only:
    # - master
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python34"
      PYTHON_EXE: "C:\\Python34/python.exe"
      IBEX_FILES: "2.3.0-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python34-x64"
      PYTHON_EXE: "C:\\Python34-x64/python.exe"
      IBEX_FILES: "2.3.0-win64"

  USERNAME:
    secure: x/KrtKQDdjxKhvPlvfdiMQ==
  PASWORD:
    secure: C5uWvbl1OHCVoprbRYTGD7LLzuUMtj18MtxytCqLmh8=

install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - cinstall: python
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON_DIR%/python.exe C:/get-pip.py"
  - ps: >-

      (new-object net.webclient).DownloadFile("https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-v2.3.57/ibex-lib-$env:IBEX_FILES.zip", 'C:\projects\pyIbex\ibex-lib.zip')

      ls C:\projects\pyIbex

      cd C:\projects\pyIbex

      7z x -tzip -oC:"ibex-lib" "C:\projects\pyIbex\ibex-lib.zip"

      ls C:\projects\pyIbex\ibex-lib
  - cmd: "%PYTHON_DIR%/python.exe -m pip install twine"

artifacts:
  - path: '**\*.whl'
    name: pip_wheel

build_script:
  - echo Running cmake..  .
  - cd c:\projects\pyIbex
  - git submodule init
  - git submodule update
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics

  - cmake -G "%CMAKE_PLATFORM%" -DPYTHON_INCLUDE_DIR:PATH=%PYTHON_DIR%/include -DPYTHON_LIBRARY:FILEPATH=%PYTHON_DIR%/libs/python34.lib -DPYTHON_EXECUTABLE:FILEPATH=%PYTHON_DIR%/python.exe -DIBEX_ROOT=C:\projects\pyIbex\ibex-lib\ibex-lib-"%IBEX_FILES%"
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% INSTALL.vcxproj
  - ctest -C %Configuration%
  - msbuild %MSBuildOptions% src/pip_package.vcxproj
  # - msbuild %MSBuildOptions% src/install_python.vcxproj


deploy:

- provider: GitHub

  auth_token:

    secure: wIeJZ9xcTslfsgvqCGez8oOC0YxhmM8LI0iJ7gBgsI7ykVeWWLEFfAQSIHgbac6k

  artifact: pip_wheel

  draft: true
  # - ps: >-
  #
  #     $env:PYTHON_EXE -m twine upload --skip-existing -m $env:USERNAME -p $env:PASSWORD $artifacts[pip_wheel].path
# https://ci.appveyor.com/api/projects/benEnsta/pyIbex/artifacs/pyibex-1.5.0rc3-cp34-cp34m-win32.whl
# deploy:
#   release: pyIbex-v$(appveyor_build_version)
#   description: 'pyIbex build'
#   provider: GitHub
#   secure: pGwTVUGtTWvmeUVLEVifu3BP2Bxu++BMAKFSs2jt3hdrsEOgvv+XgJx/W+cPFdFl
#   artifact: pip_wheel
#   draft: true
#   auth_token:
#   prerelease: false
#   on:
#     branch: appveyor      # release from master branch only
#     appveyor_repo_tag: false        # deploy on tag push only




# curl -L "https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-v2.1.17/ibex-lib-2.1.12-win64.exe" -o "C:\projects\pyIbex\ibex-lib.exe"
# ls C:\projects\pyIbex
# cd C:\projects\pyIbex
# ibex-lib.exe /D="C:\projects\pyIbex"
# ls "C:\projects\pyIbex"

# curl -L "https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-v2.1.17/ibex-lib-2.1.12-win64.zip" -o "C:\projects\pyIbex\ibex-lib.zip"
# ls C:\projects\pyIbex
# 7z x -tzip -oC:"C:\projects\pyIbex\ibex-lib" "C:\projects\pyIbex\ibex-lib.zip"
# ls C:\projects\pyIbex\ibex-lib
