version: 1.5.{build}
os: Visual Studio 2015
clone_folder: C:\projects\pyIbex
test: off
configuration:
    - Release
    # - Debug
# branches:
  # only:
    # - master

environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
    2.7.4: 2.7.4
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python34"
      PYTHON_EXE: "C:\\Python34/python.exe"
      IBEX_FILES: "2.7.4-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python35"
      PYTHON_EXE: "C:\\Python35/python.exe"
      IBEX_FILES: "2.7.4-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python36"
      PYTHON_EXE: "C:\\Python36/python.exe"
      IBEX_FILES: "2.7.4-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python34-x64"
      PYTHON_EXE: "C:\\Python34-x64/python.exe"
      IBEX_FILES: "2.7.4-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_EXE: "C:\\Python35-x64/python.exe"
      IBEX_FILES: "2.7.4-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python36-x64"
      PYTHON_EXE: "C:\\Python36-x64/python.exe"
      IBEX_FILES: "2.7.4-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python37-x64"
      PYTHON_EXE: "C:\\Python37-x64/python.exe"
      IBEX_FILES: "2.7.4-win64"

  USERNAME:
    secure: x/KrtKQDdjxKhvPlvfdiMQ==
  PASWORD:
    secure: C5uWvbl1OHCVoprbRYTGD7LLzuUMtj18MtxytCqLmh8=
  FTP_PASSWD:
    secure: U58Tazcrcj6n+oP1CxfRCQ==

install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - cmd: "%PYTHON_EXE% -m pip install --disable-pip-version-check --user --upgrade pip wheel"
  - cmd: echo "https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-2.7.4/ibex-lib-$env:IBEX_FILES.zip"
  - ps: >-

      (new-object net.webclient).DownloadFile("https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-2.7.4/ibex-lib-$env:IBEX_FILES.zip", 'C:\projects\pyIbex\ibex-lib.zip')

      ls C:\projects\pyIbex

      cd C:\projects\pyIbex

      7z x -tzip -oC:"ibex-lib" "C:\projects\pyIbex\ibex-lib.zip"

      ls C:\projects\pyIbex\ibex-lib

  # - cmd: "%PYTHON_DIR%/python.exe -m pip install twine"

artifacts:
  - path: '**\*.whl'
    name: pip_wheel

build_script:
  - echo Running cmake..  .
  - cd c:\projects\pyIbex
  - git submodule init
  - git submodule update
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics

  - cmake -G "%CMAKE_PLATFORM%"  -DPYBIND11_CPP_STANDARD=/std:c++14 -DPYTHON_INCLUDE_DIR:PATH=%PYTHON_DIR%/include -DPYTHON_LIBRARY:FILEPATH=%PYTHON_DIR%/libs/python34.lib -DPYTHON_EXECUTABLE:FILEPATH=%PYTHON_DIR%/python.exe -DIBEX_ROOT=C:\projects\pyIbex\ibex-lib\ibex-lib-"%IBEX_FILES%"
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% INSTALL.vcxproj
  - ctest -C %Configuration% -VV
  - msbuild %MSBuildOptions% src/pip_package.vcxproj

deploy:
  provider: FTP
  protocol: ftp
  host: bdesroch.privatedns.org
  username: git
  password:
    secure: U58Tazcrcj6n+oP1CxfRCQ==
  folder: gittmp/win
  artifact: pip_wheel
